### PR TITLE
fixed register -> login model structure mismatch

### PR DESCRIPTION
**Pull request by iamjoanne**

### CODE REVIEW

**Comment by circuitrider** [comment]
Actually, that second fix isn't right. I just fixed it in your repo and you'll have to approve, and cancel/update changeset 7697c66. I will need to test why that ui issue happens, it isn't obvious when I look at it right now.

**Comment by iamjoanne** [comment]
How do I approve/cancel,update changes?

By the way, thanks for the lessons last week!

**Comment by circuitrider** [comment]
Sorry. I already fixed this and another thing. I forgot to send you a pull request. The change I made create a custom fork in my repo which I never sent to you to merge into your branch. 

Just cancel this pull request and merge to my latest version and it will fix the bug locally.

**Comment by iamjoanne** [comment]
do i have to cancel on github then i can merge or just merge?

**Comment by circuitrider** [comment]
I think you can just merge. I just closed the pull request.

**Comment by iamjoanne** [comment]
ok cool thanks

**Pull request closed without merging**
